### ISSUE TITLE
Section 7.2.2 - Dynamic linking

### ISSUE THREAD

**Issue by auermich93** [cggallant/WebAssembly-in-Action#2]
Hi,

I am trying to build the code of section 7.2.2 on my Windows 10 machine, using Firefox Browser 84.0.2. However, running
the code shows the following output:
![webassembly](https://user-images.githubusercontent.com/15944908/104961128-019ef480-59d6-11eb-93c5-f9c1129ac14f.PNG)

The compilation process doesn't expose any warning or error using the latest SDK. I have also tried the code directly from the repository and even a simplified version of it, but the error remains. Even tried to use Internet Explorer but without success.
I am using the suggested `emrun` command for spawning a simple web server.

Any help is appreciated!

**Comment by cggallant** [comment]
I'm able to reproduce the issue using `emrun` but I'm not certain why it's not working. I'll do some digging.

For now, you could try using the **wasm-server.py** file that matches your setup (python 2.5 or 3): [https://github.com/cggallant/blog_post_code/tree/master/2020%20-%20July%20-%20Extending%20Python%E2%80%99s%20Simple%20HTTP%20Server](https://github.com/cggallant/blog_post_code/tree/master/2020%20-%20July%20-%20Extending%20Python%E2%80%99s%20Simple%20HTTP%20Server)

I drop the wasm-server.py file into the folder with the html file, open a command prompt and navigate to the file and then run the following command: `python wasm-server.py`

After that, open the browser and type: `http://localhost:8080/main.html`

**Comment by auermich93** [comment]
Thanks, the suggested work-around does its job.
