### ISSUE TITLE
Section 9.4: issue about pthreads.html

### ISSUE THREAD

**Issue by daem0nc0re** [cggallant/WebAssembly-in-Action#4]
Hi.

I tested updated codes for Section 9.4 but hit following error.

```
Uncaught ReferenceError: SharedArrayBuffer is not defined
```

The error is outputted in developer tool console of FireFox and Google Chrome.
I build it with Emscripten 2.0.28.
How can I fix it?

**Comment by cggallant** [comment]
The SharedArrayBuffer is disabled by default but can be enabled if you specify the following headers: 
- `Cross-Origin-Opener-Policy` _(COOP)_ set to `same-origin`
- `Cross-Origin-Embedder-Policy` _(COEP)_ set to `require-corp`

If you have any links to items in a CDN, you'll need to add `crossorigin` to the link tag.

More details about these changes can be found in my article here: [https://cggallant.blogspot.com/2020/07/webassembly-threads-in-firefox.html](https://cggallant.blogspot.com/2020/07/webassembly-threads-in-firefox.html)

I've included a Python script `wasm-server.py` at the root of this repo that has those headers set and can be run by navigating to the root of the solution in your terminal window and running the following command: **python wasm-server.py**

**Comment by daem0nc0re** [comment]
Thanks!
